### ISSUE TITLE
[feature]: lancedb driver class

### ISSUE THREAD

**Issue by Aisuko** [SkywardAI/voyager#22]
CURD operations of vector db.

Please keep in mind:

* The connection of db can be reused(we need init only one connection of db and keep it alive)
* Any operation of db should be committed before the next operation coming
* Graceful close the connection in any situation.

**Comment by Aisuko** [comment]
Please split this issue to many of sub-issues. @cbh778899

**Comment by cbh778899** [comment]
> Please split this issue to many of sub-issues. @cbh778899

No worries, LanceDB does all automatically, I'll add a function to get table from opened connection and we just use the built-in functions for query
