### ISSUE TITLE
[feature]: new API to query all the versions of the services.

### ISSUE THREAD

**Issue by Aisuko** [SkywardAI/voyager#24]
https://github.com/SkywardAI/voyager/blob/d4837b1553cbb63242882a98357c143ec31e2cbf/Makefile#L37-L50

WE want to build  a API and the activity like below

    def test_api_version(self):
        """
        Test the version API
        """
        response = self.client.get("/version")
        assert response.status_code == 200
        assert response.json() == {
            "inferenceEngine": "server--b1-2321a5e",
            "milvus": "v2.3.12",
            "kirin": "v0.1.19",
        }

https://github.com/SkywardAI/kirin/blob/9cdf258adfb960d309e4af91fe6ff2c01ae555d0/backend/tests/unit_tests/test_api_version.py#L37-L47

- [ ] API implementation
- [ ] Test case implementation

**Comment by Murkeee** [comment]
At the moment only the Inference version is defined in env. Is this the only service i need to account for at the moment?

**Comment by Aisuko** [comment]
> At the moment only the Inference version is defined in env. Is this the only service i need to account for at the moment?

I believe it's fine. How about you? Do you want to add more? @cbh778899

**Comment by cbh778899** [comment]
> INFERENCE_ENG_VERSION

Yup this one is fine, the embedding eng and inference eng are using the same version, so either of them is enough...It is possible to include also the version of API itself, but like the rebel project, it has to be updated everytime we publish a new version, and it is included in the API doc, so perhaps no need.
