### ISSUE TITLE
[Feature]: Add JSDoc for the inference feature

### ISSUE THREAD

**Issue by Aisuko** [SkywardAI/voyager#39]
### What feature are you requesting?

We want to add code comment for inference function to make the contribution easier.

https://github.com/SkywardAI/voyager/blob/dda976d60b40eea77078fabf822325d36b90727a/actions/inference.js#L21-L46

**Comment by cbh778899** [comment]
No worries about this, it is just for the completed inference routes to generate an OpenAI like response, nothing else should use this function.

**Comment by ZYLIII** [comment]
I'll take this

**Comment by cbh778899** [comment]
See [JSDoc](https://jsdoc.app/about-getting-started) for more information.
