### ISSUE TITLE
[Feature]: Justify to quick-start platform

### ISSUE THREAD

**Issue by cbh778899** [SkywardAI/voyager#42]
### What feature are you requesting?

We are going to make Voyager project a small platform with simple setup steps to deploy.

Here are some ideas:
- Add `.env.production` file, includes production settings, fields can be considered: 
  - `ALLOW_ORIGIN`: To set the only origin can be accessed.
  - `AVAILABLE_APIS`: To set APIs available in production, other APIs won't be added to route table.
  - `STATIC_API_KEY_ENABLED`: If set to true, find static api key in server environmental variables and validate if passed api key is correct.
- More to add...

Please comment here about your thoughts.
cc @Aisuko

**Comment by Aisuko** [comment]
@cbh778899 COOL
