### ISSUE TITLE
[Feature]: Add real token count in response when using inference

### ISSUE THREAD

**Issue by cbh778899** [SkywardAI/voyager#51]
### What feature are you requesting?

-

**Comment by NguyenNguyen205** [comment]
Hi, when I examine the project and running it in Docker container, I notice that the response from the llama server also contain the tokens predicted and tokens evaluated value like in the screenshot, but I'm not sure if these are the real tokens count you need for this issue ?
![image](https://github.com/user-attachments/assets/fffd5581-7579-48e9-8f42-717b5b8abd32)

**Comment by cbh778899** [comment]
Correct, this is basically what we need to add inside the response as part of token management. Fell free to add it and pin me in PR.
