### ISSUE TITLE
[Feature]: A simple UI for developer testing API

### ISSUE THREAD

**Issue by Aisuko** [SkywardAI/voyager#53]
### What feature are you requesting?

Please add a simple_ui https://github.com/Aisuko/chatpilot/blob/main/demo_ui.py to our project under example folder. It aims for new contributor easier to do contribution. The `demo_ui` I mentioned above also support to invoke our project chat API, this is the next step.

Free to change the content on the `demo_ui.py` file.

- [x] Add `demo_ui.py` to the project  @ZooHigher26  https://github.com/SkywardAI/voyager/pull/68
- [x] Add/test inference API for the demo_ui.py @ZYLIII  https://github.com/SkywardAI/voyager/pull/84
- [x] Replace user name to your team name @ZooHigher26  https://github.com/SkywardAI/voyager/pull/80
- [x] Replace the RMIT icon to your specific icon @ZooHigher26  https://github.com/SkywardAI/voyager/pull/80
- [x] Replace the  `Customary xxxxxx: chatbot` to your project name @ZooHigher26 https://github.com/SkywardAI/voyager/pull/68
- [ ] Add technical document(how to run ui locally) @s3861232 https://github.com/SkywardAI/voyager/pull/85
- [x] Replace the original image to a new image @ZooHigher26 https://github.com/SkywardAI/voyager/pull/80

**No need to rush time. This is a good chance to familiar the code.**

**Comment by knframe2** [comment]
.

**Comment by ZooHigher26** [comment]
Happy to do "Replace the Customary xxxxxx: chatbot to your project name" or any other task/s.

**Comment by Aisuko** [comment]
@ZooHigher26 You can add https://github.com/Aisuko/chatpilot/blob/main/demo_ui.py  to this project. And do a PR for it.  And then replace the name on it and do another PR.

**Comment by ZooHigher26** [comment]
By adding, do you mean adding it to Voyager?

**Comment by ZooHigher26** [comment]
Do I just add demo_ui.py or do I need to add all the files as well?

**Comment by Aisuko** [comment]
> Do I just add demo_ui.py or do I need to add all the files as well?

Only add single file demo_ui.py

**Comment by Aisuko** [comment]
@ZYLIII 

https://github.com/SkywardAI/voyager/blob/a5eba687b6f684222ddbf5c638c8ee2525d6a386/example/test_apis.py#L27-L55

**Comment by Aisuko** [comment]
Replace the image 

- [ ] Upload specific log to `example/img`
- [ ] Replace path of image 

https://github.com/SkywardAI/voyager/blob/a5eba687b6f684222ddbf5c638c8ee2525d6a386/example/demo_ui.py#L65

**Comment by ZooHigher26** [comment]
Can I still do any tasks that haven't been assigned?

**Comment by Aisuko** [comment]
> Can I still do any tasks that haven't been assigned?

Yes, totally welcome. Let me invite you as a collaborator of the SkywardAI Org.

**Comment by Aisuko** [comment]
@cbh778899 May you create some issues of the update events pages? Please split the tasks into small chunk that will easier for our new collaborators to do contribution.

**Comment by cbh778899** [comment]
That's different, not belongs to this project...

**Comment by Aisuko** [comment]
You are right. May you create new issues that in the roadmap?

**Comment by ZooHigher26** [comment]
I'm not sure how to remove the older commits, will this be an issue?

**Comment by cbh778899** [comment]
> I'm not sure how to remove the older commits, will this be an issue?

The next time please pull the latest main branch, start a new branch from main or rebase the main branch to your working branch, that can avoid having strange history commits. This should be fine for now.

**Comment by ZooHigher26** [comment]
@Aisuko I created a new branch and updated the files but it's still showing the previous commit history.
![image](https://github.com/user-attachments/assets/f58c02bf-8c74-45ec-bcb5-398a689bfb83)
![image](https://github.com/user-attachments/assets/f5cd3d29-1064-48ce-bc50-8fad2520682a)
Would it be easier to delete the fork, fork the repo again and then make the necessary changes?

**Comment by Aisuko** [comment]
Hi @ZooHigher26, yes, feel free to do it. And also, I believe you have "write" permission of voyager which means you can clone this repo directly, and push a new branch. And the new branch can be create a PR.

**Comment by ZooHigher26** [comment]
@Aisuko I think I managed to fix the issues with the commit history, but not 100% sure if it was the right way to do it. I just created a new branch named UI features and then created a pull request from that.

**Comment by Aisuko** [comment]
For technical document
https://github.com/Aisuko/chatpilot/blob/f66266eec6fe0a48f7ecc5fd699cac896d2ede88/.vscode/launch.json#L22C3-L31C10

**Comment by s3861232** [comment]
This is Paveenuch

**Comment by Murkeee** [comment]
@s3861232 let us know if you need help with your task :)

**Comment by s3861232** [comment]
@Murkeee Thank you so much. Appreciate it. I should be able to work on it tonight. Just came back from holiday ^^
