### ISSUE TITLE
[Feature]: Inference with few-short learning approach.

### ISSUE THREAD

**Issue by Aisuko** [SkywardAI/voyager#57]
### What feature are you requesting?

Currently, I found the new base line SML response is lower quality in this project. The response quality is lower than https://www.youtube.com/watch?v=oN55EJ3L3wc. In this video, I asked it some random questions. And it uses few-short learning.

https://github.com/Aisuko/chatpilot/blob/d6ed14ed69e7821fc3f9d9c70d03182ed5fe902a/demo_ui.py#L74C1-L83C6

So, please update the way of using SML to using few-short learning approach.

**More for few-short approach**

* https://arxiv.org/pdf/2103.00020

**Comment by cbh778899** [comment]
Seems like it do works with the small language model. I would consider add it when selected this model.
