### ISSUE TITLE
[Bug]: RAG inference context null

### ISSUE THREAD

**Issue by Murkeee** [SkywardAI/voyager#62]
### What happened?

When making request to inference API for RAG completion the context is always null.

### Version

v0.2.1

### Relevant log output

```shell
[nodemon] starting `node --disable-warning=ExperimentalWarning index.js`
VOYAGER is running on port 8000, happy sailing!
file:///app/actions/inference.js:227
        { role: "system", content: `This background information is useful for your next answer: "${rag_result.context}"` }
                                                                                                              ^

TypeError: Cannot read properties of null (reading 'context')
    at ragChatCompletion (file:///app/actions/inference.js:227:111)

Node.js v20.15.1
```

**Comment by Murkeee** [comment]
@cbh778899 @Aisuko

**Comment by cbh778899** [comment]
In the latest version, you should load the dataset first using `POST /v1/embeddings/dataset` and call the rag engine with the loaded dataset name. Still, I'll add validation on null values later.

**Comment by Aisuko** [comment]
@cbh778899 Do we have some demo for how to load dataset? like video, or test case? If not, may you create an issue for it?

**Comment by cbh778899** [comment]
just run the `try it out` in swagger docs can load the dataset, the variables are written there

**Comment by Aisuko** [comment]
Here is the new video https://github.com/SkywardAI/voyager?tab=readme-ov-file#setup-and-api-usage-demo-video and it includes how to load the data from Swagger cc @Murkeee
